version: '3.9'
services:
  mysql:
    image: mysql:8.4.1
    container_name: htqlhh_db
    environment:
      MYSQL_ROOT_PASSWORD: root@12345678
      MYSQL_DATABASE: htqlcv
      MYSQL_USER: htqlcv
      MYSQL_PASSWORD: 12345678
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - '3307:3306'
    networks:
      - proxy_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uhtqlcv", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    container_name: htqlhh_redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6378:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis/data:/data
    networks:
      - proxy_network

  backend:
    container_name: htqlhh_backend
    image: hoangtuanhcmus/dev:htqlhh_backend_v13
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - proxy_network
  frontend:
    container_name: htqlhh_frontend
    image: hoangtuanhcmus/dev:htqlhh_frontend_v25
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - proxy_network
  aiService:
    container_name: htqlhh_aiService
    image: hoangtuanhcmus/dev:htqlhh_aiService_v4
    ports:
      - 8001:8001
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ENV: prod
      DEBUG_MODE: True
      HOST: localhost
      PORT: 8001
      PROJECT_NAME: AI SERVICE
      PROJECT_VERSION: 1.0.0
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: htqlcv
      MYSQL_PASSWORD: 12345678
      MYSQL_DB: htqlcv
      LANGSMITH_TRACING: true
      LANGSMITH_API_KEY: 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
      LANGSMITH_PROJECT: default
      GOOGLE_API_KEY: AIzaSyCouB8i4EIecncz8fPKGYtqYqlpa-FgiKo
    networks:
      - proxy_network


networks:
  proxy_network:
    external: true
