version: '3.8'
# sudo certbot certonly --standalone -d hethongquanlybanle.xyz
#cp -r /etc/letsencrypt/* ./certbot/ssl/ 
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/ssl/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - proxy_network
#  certbot:
#    image: certbot/certbot:latest
#    container_name: certbot
#    command: certonly --webroot -w /var/www/certbot --force-renewal --email pnhtuanhcmus@gmail.com -d hethongquanlybanle.xyz --agree-tos --post-hook "chmod -R 755 /etc/letsencrypt/live /etc/letsencrypt/archive"
#    volumes:
#      - ./certbot/www/:/var/www/certbot/
#      - ./certbot/ssl/:/etc/letsencrypt/
networks:
  proxy_network:
    external: true
